delySantiago/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('delysantiago', include('apps.DelySantiago.urls')),
    path('registro/', include('apps.Registro.urls')),
    path('usuario/', include('apps.Usuario.urls')),
    # Login and Logout
    path('login/', LoginView.as_view(redirect_authenticated_user=True,template_name='Usuario/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='Usuario/logout.html'), name='logout'),
    path('', TemplateView.as_view(template_name='delysantiago/home.html'), name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/Registro/models.py
from django.db import models

# Create your models here.

class Proveedor(models.Model):
    nombre = models.CharField(max_length=50)
    email = models.EmailField()
    numero = models.IntegerField()
    
    def __str__(self):
        return self.nombre
        
class Plato(models.Model):
    nombre = models.CharField(max_length=50)
    precio = models.IntegerField()
    ingredientes = models.TextField()
    descripcion = models.TextField()
    proveedor = models.ForeignKey(Proveedor, on_delete=models.PROTECT)
    imagen = models.ImageField(upload_to="platos", null=True)
    
    def __str__(self):
        return self.nombre

templates/base.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <!-- Font Courgette -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Courgette&display=swap" rel="stylesheet">
    <!-- Font Cinzel -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Cinzel&display=swap" rel="stylesheet">
    {% load static %}
    {% block css %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'base/css/base.css' %}">
    <title>Dely Santiago</title>
</head>

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">Dely Santiago</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav m-auto my-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tienda' %}">Tienda</a>
                    </li>
                    {% if perms.registro.add_plato %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Platos
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'agregar_plato' %}">Agregar platos</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'listado_platos' %}">Lista de platos
                                    (editar/eliminar)</a></li>
                        </ul>
                    </li>
                    {% endif %}
                    {% if perms.registro.add_plato %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Proveedores
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'agregar_proveedor' %}">Agregar proveedor</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'listado_proveedores' %}">Lista de proveedores
                                    (editar/eliminar)</a></li>
                        </ul>
                    </li>
                    {% endif %}
                </ul>
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a id="login" class="nav-link" href="#">@{{ user.username }}</a>
                    </li>
                    <li class="nav-item">
                        <a id="login" class="nav-link" href="{% url 'logout' %}">Cerrar Sesion</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a id="login" class="nav-link" href="{% url 'login' %}">Ingresar</a>
                    </li>
                    <li class="nav-item">
                        <a id="login" class="nav-link" href="{% url 'registrar' %}">Registrate</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <!-- <div class="mensaje">
        {% if messages %}
        {% for m in messages %}
        {{m}}
        {% endfor %}
        {% endif %}
    </div> -->
    {% block contenido %}

    {% endblock %}
    <!-- Footer -->
    <div class="row footer">
        <div class="col-sm-4 footer-logo">
            <h1>Dely Santiago</h1>
        </div>
        <div class="col-sm-4 footer-num">
            <h2>+569 51 23 56 23</h2>
        </div>
        <div class="col-sm-4 footer-icons">
            <img class="footer-ico" src="{% static 'base/ico/facebook.svg' %}" alt="...">
            <img class="footer-ico" src="{% static 'base/ico/instagram.svg' %}" alt="...">
            <img class="footer-ico" src="{% static 'base/ico/twiter.svg' %}" alt="...">
        </div>
    </div>

    </div>
    <!-- Popper -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js"
        integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT"
        crossorigin="anonymous"></script>
    <!-- SweetAlert2 -->
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    {% if messages %}
    {% for m in messages %}
    <script>Swal.fire({
            "title": "Felicitaciones",
            "text": "{{m}}",
            "icon": "success"
        })
    </script>
    {% endfor %}
    {% endif %}
    {% block js %}
    {% endblock %}
</body>

</html>